<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Spisanie.Updater</RootNamespace>
    <AssemblyName>Spisanie.Updater</AssemblyName>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
